### ISSUE TITLE
Example infrastructure routing problem

### ISSUE THREAD

**Issue by cbankston** [s-maj/aws-transit-vpc#2]
Hi @s-maj !

I've been playing around with the example infrastructure in this project and am struggling to get it to work completely. My networking skills are not very strong and I have run out of ideas for debugging this issue. 

Do you know what would cause the following behavior?
1) The AWS VPN tunnels are established, they are not flapping, but they do show `0 BGP ROUTES`
2) I can't figure out how to route traffic through the AWS VPN connection, even if I add some static routes to the routing tables myself

Here's a screenshot of a ping test from `probe-nvirginia` to `probe-oregon`, along with tcpdump output from all of the test servers:
![ping-from-probe-to-probe](https://user-images.githubusercontent.com/353273/38642268-ce385298-3d96-11e8-827a-c71e13fe4a92.png)

Here's a screenshot of a ping test from `vpn-1` to `probe-oregon`, along with tcpdump output from all of the test servers:
![ping-from-vpn-to-probe](https://user-images.githubusercontent.com/353273/38642319-f5b3ccc6-3d96-11e8-826f-3dab3560de02.png)

Here's a screenshot of my AWS VPN connection details for this tunnel:
![aws_vpn_description](https://user-images.githubusercontent.com/353273/38642367-1696fa1c-3d97-11e8-93df-0fccef6f911a.png)

I tried to add some static routing to see if that would help, but the results were the same.
![2018-04-11_13-21-05](https://user-images.githubusercontent.com/353273/38642489-77f41c18-3d97-11e8-9e06-c5c51756c961.png)

I had to make a few changes to get the example infrastructure in this project up and running in my AWS account and have submitted the changes for your review over here:
https://github.com/s-maj/aws-transit-vpc/pull/1

I would appreciate any leads you may have. Thanks for your time!

**Comment by s-maj** [comment]
Alright, first try to ping left/right end of the tunnel (don't know which one is your end): 
 169.254.23.237 or 169.254.23.238. If that works, take a look [here](https://aws.amazon.com/premiumsupport/knowledge-center/check-vpn-tunnel-status/l) from the `If you are using a BGP VPN:`. If the tunnel is UP but no routes being propagated probably BIRD daemon is down/unhappy.  Check logs in `/var/log/bird.log` and `/var/log/messages/syslog`.
